// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type CategoryCreate = {
    nombre: string;
    is_active?: boolean;
};

export type CategoryPublic = {
    id: string;
    nombre: string;
    is_active?: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type CategoryUpdate = {
    nombre?: (string | null);
    is_active?: boolean;
};

export type SectionCreate = {
    nombre: string;
    category_id: string;
    is_active?: boolean;
};

export type SectionPublic = {
    id: string;
    nombre: string;
    category_id: string;
    is_active?: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SectionUpdate = {
    nombre?: (string | null);
    category_id?: (string | null);
    is_active?: boolean;
};

export type SubSectionCreate = {
    nombre: string;
    section_id: string;
    is_active?: boolean;
};

export type SubSectionPublic = {
    id: string;
    nombre: string;
    section_id: string;
    is_active?: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SubSectionUpdate = {
    nombre?: (string | null);
    section_id?: (string | null);
    is_active?: boolean;
};

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (Array<CategoryPublic>);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type SectionsReadSectionsData = {
    limit?: number;
    skip?: number;
};

export type SectionsReadSectionsResponse = (Array<SectionPublic>);

export type SectionsCreateSectionData = {
    requestBody: SectionCreate;
};

export type SectionsCreateSectionResponse = (SectionPublic);

export type SectionsReadSectionData = {
    sectionId: string;
};

export type SectionsReadSectionResponse = (SectionPublic);

export type SectionsUpdateSectionData = {
    sectionId: string;
    requestBody: SectionUpdate;
};

export type SectionsUpdateSectionResponse = (SectionPublic);

export type SectionsDeleteSectionData = {
    sectionId: string;
};

export type SectionsDeleteSectionResponse = (Message);

export type SubSectionsReadSubSectionsData = {
    limit?: number;
    skip?: number;
};

export type SubSectionsReadSubSectionsResponse = (Array<SubSectionPublic>);

export type SubSectionsCreateSubSectionData = {
    requestBody: SubSectionCreate;
};

export type SubSectionsCreateSubSectionResponse = (SubSectionPublic);

export type SubSectionsReadSubSectionData = {
    subSectionId: string;
};

export type SubSectionsReadSubSectionResponse = (SubSectionPublic);

export type SubSectionsUpdateSubSectionData = {
    subSectionId: string;
    requestBody: SubSectionUpdate;
};

export type SubSectionsUpdateSubSectionResponse = (SubSectionPublic);

export type SubSectionsDeleteSubSectionData = {
    subSectionId: string;
};

export type SubSectionsDeleteSubSectionResponse = (Message);