"""Add sections table

Revision ID: 06edada5c509
Revises: 1d41fe751270
Create Date: 2026-04-13 16:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06edada5c509'
down_revision = '1d41fe751270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sections',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('category_id', sa.Uuid(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre', 'category_id')
    )
    op.create_index(op.f('ix_sections_category_id'), 'sections', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_category_id'), table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###