"""Add sub_sections table

Revision ID: d6d74667522f
Revises: 06edada5c509
Create Date: 2026-04-13 16:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d74667522f'
down_revision = '06edada5c509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sub_sections',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('section_id', sa.Uuid(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['section_id'],
            ['sections.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre', 'section_id')
    )
    op.create_index(op.f('ix_sub_sections_section_id'), 'sub_sections', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_sections_section_id'), table_name='sub_sections')
    op.drop_table('sub_sections')
    # ### end Alembic commands ###